---
name: File-Find-Rule-SAUCE
version: 0.06
author:
  - 'Brian Cassidy <bricas@cpan.org>'
abstract: "Rule to match on title, author, etc from a file's SAUCE record"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Find::Rule: 0
  File::SAUCE: 0.1
build_requires:
  Test::More: 0
provides:
  File::Find::Rule::SAUCE:
    file: lib/File/Find/Rule/SAUCE.pm
    version: 0.06
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
