# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Find-Rule-SAUCE
version:      0.04
version_from: lib/File/Find/Rule/SAUCE.pm
installdirs:  site
requires:
    File::Find::Rule:              0
    File::SAUCE:                   0.1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
